platform :ios, '7.0'

pod 'CocoaLumberjack', '~> 2.0.1'
pod 'FMDB', '~> 2.5'
pod 'FXBlurView', '~> 1.6.3'
pod 'QRCodeReaderViewController', '~> 3.5.2'
pod 'AFNetworking', '~> 2.5.4'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Reachability', '~> 3.2'
pod 'JTCalendar', '~>1.2.3'
pod 'CWPopup', '~> 1.2.4'
pod 'SSZipArchive', '~>0.3.2'
pod 'ObjectiveSugar', '~> 1.1.0'