platform :ios, '7.0'

pod 'CocoaLumberjack'
pod 'FMDB'
pod 'FXBlurView'
pod 'QRCodeReaderViewController'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'Reachability'
pod 'JTCalendar'
pod 'CWPopup', '~> 1.2.4'
pod 'SSZipArchive', '~>0.3.2'